---
title: "olympics"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F, warning = F}
library(tidyverse)
library(skimr)

theme_set(theme_light())

data <- tidytuesdayR::tt_load('2021-07-27')
olympics <- data$olympics

rm(data)

```


```{r}

skim(olympics)

```


```{r}

olympics %>% 
  summarise(years = unique(year)) %>% 
  arrange(years) %>% 
  pull(years)


summer_olympics <- olympics %>% 
  filter(season == "Summer")

```

# Athletes with the greatest number of medals

```{r}

most_medals <- summer_olympics %>% 
  filter(!is.na(medal)) %>% 
  count(name, sort = TRUE) %>% 
  slice_max(n, prop = 0.001)


most_medals %>% 
  ggplot(aes(reorder(name, n), n)) +
  geom_col(fill = "#272F49", color = "#676D7F") +
  coord_flip() +
  labs(x = NULL, y = "Number of olympic medals",
       title = "Top 0.1% of olympic athletes",
       subtitle = "Ordered by total number of medals")
  

```

# Countries with the greatest number of medals

```{r}


countries_most_medals <- summer_olympics %>% 
  filter(!is.na(medal)) %>% 
  count(team, sort = TRUE) %>% 
  slice_max(n, prop = 0.05)


countries_most_medals %>% 
  ggplot(aes(reorder(team, n), n)) +
  geom_col(fill = "#272F49", color = "#676D7F") +
  coord_flip() +
  labs(x = NULL, y = "Number of olympic medals",
       title = "Top 5% of olympic teams in history",
       subtitle = "Ordered by total number of medals")

```


# Average height by team

```{r}

height_team <- summer_olympics %>% 
  group_by(team) %>% 
  summarise(avg_height = mean(height)) %>% 
  drop_na(avg_height) %>% 
  arrange(desc(avg_height)) %>% 
  slice_max(avg_height, prop = 0.2)

height_team %>% 
  ggplot(aes(reorder(team, avg_height), avg_height)) +
  geom_col() +
  coord_flip()
  


```


# Top 5% sports by number of delivered medals, in history

```{r}

events_most_medals <- summer_olympics %>% 
  drop_na(sport, medal) %>% 
  group_by(sport) %>% 
  count(medal, name = "total_medals")

events_most_medals %>% 
  ggplot(aes(medal, reorder(sport, total_medals), fill = total_medals)) +
  geom_tile() +
  scale_fill_gradient(low = "#a4dab7", high = "#272f49") +
  labs(title = "Athletics is the sport that delivered the most medals",
       subtitle = "Considering all events in history", x = NULL,
       y = "Olympic Event", fill = "Total number of medals")
  

```


# Sports ordered by average height, from low to high

```{r}

avg_height <- summer_olympics %>% 
  drop_na(height) %>% 
  group_by(sport, sex) %>% 
  mutate(sex_sport_avg_height = mean(height))

avg_height <- avg_height %>% 
  ungroup() %>% 
  group_by(sport) %>% 
  mutate(sport_avg_height = mean(height)) %>% 
  select(sex, sport, sex_sport_avg_height,
         sport_avg_height) %>% 
  distinct()

both_sexes_avg_height <- avg_height %>% 
  select(sport, sex_sport_avg_height = sport_avg_height) %>% 
  mutate(sex = "Both") %>% 
  distinct()


avg_height <- avg_height %>% 
  select(-sport_avg_height) %>% 
  bind_rows(both_sexes_avg_height) %>% 
  arrange(sport, sex)
  

  
height_plot <- avg_height %>% 
  ggplot() +
  geom_point(aes(reorder(sport, sex_sport_avg_height), sex_sport_avg_height,
             color = sex, group = sex)) +
  geom_line(aes(reorder(sport, sex_sport_avg_height), sex_sport_avg_height,
             color = sex, group = sex))
  
height_plot +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "Sport", y = "Average height", color = "Sex",
       title = "Gymnastics and Basketball are on the extremes of average athlete height",
       subtitle = "Considering all summer olympic sports") 
  
```

# Sports ordered by average weight, from low to high

```{r}

avg_weight <- summer_olympics %>% 
  drop_na(weight) %>% 
  group_by(sport, sex) %>% 
  mutate(sex_sport_avg_weight = mean(weight))

avg_weight <- avg_weight %>% 
  ungroup() %>% 
  group_by(sport) %>% 
  mutate(sport_avg_weight = mean(weight)) %>% 
  select(sex, sport, sex_sport_avg_weight,
         sport_avg_weight) %>% 
  distinct()

both_sexes_avg_weight <- avg_weight %>% 
  select(sport, sex_sport_avg_weight = sport_avg_weight) %>% 
  mutate(sex = "Both") %>% 
  distinct()


avg_weight <- avg_weight %>% 
  select(-sport_avg_weight) %>% 
  bind_rows(both_sexes_avg_weight) %>% 
  arrange(sport, sex)
  

  
weight_plot <- avg_weight %>% 
  ggplot() +
  geom_point(aes(reorder(sport, sex_sport_avg_weight), sex_sport_avg_weight,
             color = sex, group = sex)) +
  geom_line(aes(reorder(sport, sex_sport_avg_weight), sex_sport_avg_weight,
             color = sex, group = sex))
  
weight_plot +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "Sport", y = "Average weight", color = "Sex",
       title = "Tug-of-war is the absolute leader in average athlete weight",
       subtitle = "Considering all summer olympic sports") 


```

# Sports ordered by average age, from low to high

```{r}


avg_age <- summer_olympics %>% 
  drop_na(age) %>% 
  group_by(sport, sex) %>% 
  mutate(sex_sport_avg_age = mean(age))

avg_age <- avg_age %>% 
  ungroup() %>% 
  group_by(sport) %>% 
  mutate(sport_avg_age = mean(age)) %>% 
  select(sex, sport, sex_sport_avg_age,
         sport_avg_age) %>% 
  distinct()

both_sexes_avg_age <- avg_age %>% 
  select(sport, sex_sport_avg_age = sport_avg_age) %>% 
  mutate(sex = "Both") %>% 
  distinct()


avg_age <- avg_age %>% 
  select(-sport_avg_age) %>% 
  bind_rows(both_sexes_avg_age) %>% 
  arrange(sport, sex)
  

  
age_plot <- avg_age %>% 
  ggplot() +
  geom_point(aes(reorder(sport, sex_sport_avg_age), sex_sport_avg_age,
             color = sex, group = sex)) +
  geom_line(aes(reorder(sport, sex_sport_avg_age), sex_sport_avg_age,
             color = sex, group = sex))
  
age_plot +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(x = "Sport", y = "Average age", color = "Sex",
       title = "A few sports have an average age greater than 30",
       subtitle = "Considering all summer olympic sports") 

```

