---
title: "netflix"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message = F}
library(tidyverse)
library(scales)
library(skimr)
library(tidytext)
library(snakecase)

theme_set(theme_light())

netflix <- read_csv("netflix.csv")

```


```{r, include = F}

# tt <- tidytuesdayR::tt_load("2021-04-20")
# netflix <- tt$netflix_titles
# rm(tt)

```


```{r}
skim(netflix)
```

```{r}

netflix <- netflix %>% separate(duration, c("duration", "duration_unit"), 
                                convert = TRUE)

```


# Rating x Type

```{r, warning = F, fig.align = 'center'}

netflix %>% 
  select(type, rating) %>% 
  ggplot(aes(rating)) +
  geom_histogram(stat = "count", color = "#2F2F4C", fill = "#F2F2F7") +
  facet_wrap(~type) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "TV-14 and TV-MA represent the vast marjority of ratings",
       subtitle = "For both movies and TV shows",
       x = "Rating", y = "", 
       caption = "\n TV-14 indicates a restriction for children under 14 years old and TV-MA suggests the title may be unsuitable for children under 17")
  

```




# Rating x Genre

A title is listed in many different genres simultaneously. 


```{r, fig.align = 'center', fig.width = 10, fig.height = 6}

netflix %>% count(rating)

netflix %>% count(listed_in)

rating_genre <- netflix %>% 
  select(rating, listed_in) %>% 
  separate_rows(listed_in, sep = ", ") %>% 
  count(listed_in, rating) %>% 
  arrange(desc(n))
  

rating_genre %>% 
  ggplot(aes(rating, listed_in)) +
  geom_point(aes(size = n)) +
  coord_flip() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "",
       subtitle = "",
       x = "Rating", y = "Genre", size = "Number of titles")



```



# Director x Genre



```{r, fig.align = 'center', fig.width = 12, fig.height = 4}

director_genre <- netflix %>% 
  select(director, listed_in) %>% 
  drop_na() %>% 
  separate_rows(listed_in, sep = ", ") %>% 
  separate_rows(director, sep = ", ") %>% 
  count(listed_in, director) %>% 
  arrange(desc(n))

director_genre %>% 
  slice_max(n, prop = 0.005) %>% 
  ggplot(aes(reorder(director, -n), listed_in)) +
  geom_point(aes(size = n)) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


```

# Director x Actors

```{r, fig.align = 'center'}

director_cast <- netflix %>% 
  select(director, cast) %>% 
  drop_na() %>% 
  separate_rows(cast, sep = ", ") %>% 
  count(director, cast) %>% 
  arrange(desc(n))

director_cast %>% 
  slice_max(n, prop = 0.0005) %>% 
  ggplot(aes(reorder(director, -n), cast, size = n)) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))



```


# Rating x Year

```{r}



```


# Duration x Country

```{r, warning = F, message = F, fig.align = 'center'}

duration <- netflix %>% 
  filter(type == "Movie") %>% 
  select(duration, country, release_year) %>% 
  mutate(country = word(country, sep = fixed(", ")),
         decade = (release_year %/% 10) * 10,
         decade = as.factor(decade),
         duration = as.numeric(duration))
         

duration %>% 
  ggplot(aes(decade, duration, group = decade)) +
  geom_boxplot() +
  geom_smooth(method = "loess", se = TRUE, aes(group = 1)) 

top_countries <- duration %>% 
  count(country) %>% 
  arrange(-n) %>% 
  drop_na() %>% 
  slice_max(n, prop = 0.05) %>% 
  pull(country)

duration %>% 
  filter(country %in% top_countries) %>% 
  ggplot(aes(decade, duration)) +
  geom_boxplot(aes(group = decade)) +
  geom_smooth(method = "loess", se = TRUE, aes(group = 1)) +
  facet_wrap(~country) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))


```

